[tool.poetry]
name = "langchain-test"
version = "0.1.0"
description = "Test repository for langchain functionalities"
authors = ["sakshamshahu <sakshamshahu.work@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
